### PR TITLE
Throw proper exception from cached provider

### LINKED ISSUE #165: NetworkException not being thrown when using cached JwkProviderBuilder instead of directly UrlJwkProvider
### Describe the problem

As per: [examples](https://github.com/auth0/jwks-rsa-java/blob/master/EXAMPLES.md) we should be able to catch NetworkException when getting JWK using cached JwkProviderBuilder. But in [here](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/GuavaCachedJwkProvider.java) that error is caught and replaced with SigningKeyNotFoundException (as ExecutionException includes NetworkException):
```
@Override
public Jwk get(final String keyId) throws JwkException {
    try {
        String cacheKey = keyId == null ? NULL_KID_KEY : keyId;
        return cache.get(cacheKey, new Callable<Jwk>() {
            @Override
            public Jwk call() throws Exception {
                return provider.get(keyId);
            }
        });
    } catch (ExecutionException e) {
        throw new SigningKeyNotFoundException("Failed to get key with kid " + keyId, e);
    }
}
```
This basically recreates the issue: #79.

### What was the expected behavior?

NetworkException being thrown directly from: `JwkProviderBuilder(URL(...)).cached(...).build().get(...)` method when unable to connect to the url.

### Reproduction

- Create cached provider for some urlPath of an offline server: `val provider = JwkProviderBuilder(URL(urlPath)).cached(10, 1, TimeUnit.MINUTES).build()`
- Try to access the JWK for some keyId: `provider.get(keyId)`
- Get the SigningKeyNotFoundException: `Failed to get key with kid ****`
- Only able to trace exception.cause: `java.util.concurrent.ExecutionException: com.auth0.jwk.NetworkException: Cannot obtain jwks from url ****`

### Environment

- **Version of this library used:** 0.21.2
- **Version of Java used:** 11 (Kotlin 1.3.72)
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

### PR DESCRIPTION
**Pull request by jimmyjames**
Prior to this change, if using a cached JWK provider (the default), any exception caught when accessing the JWK would be a `SigningKeyNotFoundException`, with a cause of `ExecutionException` (thrown by the cache provider). 

Since the cause of an exception may be for different reasons (e.g., network exception, KID not found), developers would need to unwrap the `SigningKeyNotFoundException` to get the `ExecutionException`, which itself would contain the specific reason for failure (some `JwkException`). 

As raised in #165, this is cumbersome. Instead, this PR throws the causing exception directly, so that developers can more easily identify why the operation failed.

Fixes #165

### CODE REVIEW

File: src/main/java/com/auth0/jwk/GuavaCachedJwkProvider.java [hunk 1]
```diff
@@ -60,14 +59,15 @@ public GuavaCachedJwkProvider(final JwkProvider provider, long size, Duration ex
     public Jwk get(final String keyId) throws JwkException {
         try {
             String cacheKey = keyId == null ? NULL_KID_KEY : keyId;
-            return cache.get(cacheKey, new Callable<Jwk>() {
-                @Override
-                public Jwk call() throws Exception {
-                    return provider.get(keyId);
-                }
-            });
+            return cache.get(cacheKey, () -> provider.get(keyId));
```
Comment (jimmyjames) [inline src/main/java/com/auth0/jwk/GuavaCachedJwkProvider.java:62]: change to lambda syntax, no functional change

**Comment by jimmyjames** [comment]
codecov failure due to fall-thru line not being covered. Since `ExecutionException` is only thrown for checked exceptions, and `JwkProvider#get()` only throws a `JwkException`, the instance checking and fallback are a bit overly careful. The effort to test such a case does not seem worthwhile since it's not a realistic scenario and simple mocking will not work as the provider cannot throw anything other than a `JwkException`.

**Review by Widcket — APPROVED** [review]
